### ISSUE TITLE
Does the resolution of LQ images will affect the quality of results? I use the 256x256 LQ images for inference and the results are bad

### ISSUE THREAD

**Issue by PengQiTu** [JingyunLiang/HCFlow#4]

**Comment by JingyunLiang** [comment]
No, the LQ image resolution doesn't have much impact. What kind of LQ images do you use? HCFlow is trained on (bicubic LR, HR) pairs, so it can only deal with bicubic LR images.

**Comment by PengQiTu** [comment]
Thanks for your reply! The LQ image I used are degraded with gaussian noise, gaussian blur, motion blur and jpeg etc. If I use my data to train the model, can I get good results?

**Comment by JingyunLiang** [comment]
Yes, you can. It is just a domain mismatch problem, because HCFlow (trained on bicubic SR imaegs) has never seen the Gaussian blur and noise before. As shown in [BSRGAN, ICCV2021](https://github.com/cszn/BSRGAN), deep learning models have the potential to deal with complex degradation if we train them with a complex degradation model.

**Comment by PengQiTu** [comment]
Ok! Thanks for your reply, I will have a try.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jingyun ***@***.***&gt;; 
发送时间: 2021年8月24日(星期二) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JingyunLiang/HCFlow] Does the resolution of LQ images will affect the quality of results? I use the 256x256 LQ images for inference and the results are bad (#4)





 
Yes, you can. It is just a domain mismatch problem, because HCFlow (trained on bicubic SR imaegs) has never seen the Gaussian blur and noise before. As shown in BSRGAN, ICCV2021, deep learning models have the potential to deal with complex degradation if we train them with a complex degradation model.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
