### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by hbw945** [JingyunLiang/HCFlow#5]
ImportError: /home/hbw/gcc-build-5.4.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/hbw/anaconda3/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)

Is this error due to my GCC version being too low, and your version is?
looking forward to your reply!

**Comment by JingyunLiang** [comment]
I think so. My gcc version is 6.3.0

**Comment by hbw945** [comment]
Thank you!
