### ISSUE TITLE
The code implementation and the paper description seem different

### ISSUE THREAD

**Issue by xmyhhh** [JingyunLiang/HCFlow#6]
Hi, your work is excellent, but there is one thing I don't understand.

What is written in the paper is:
> "**A diagonal covariance matrix with all diagonal elements close to zero**"

But the code  implementation in HCFlowNet_SR_arch.py line 64 is: 
```basic. Gaussian diag.logp (LR, - torch. Ones_ like(lr)*6, fake_ lr_ from_ hr)  ```

why use ```- torch. Ones_ like(lr)*6``` as covariance matrix? This seems to be inconsistent with the description in the paper

**Comment by JingyunLiang** [comment]
As you can see, it is the `logp`. `(logp -> -6) == (p -> 0)`. We use this trick for numerical stability.

**Comment by xmyhhh** [comment]
I get it！！    thanks~
